contratar_musicos/main/urls.py
from django.urls import include, path
from django.contrib import admin
from contratar_musicos.main import views
from django.contrib.auth import views as auth_views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('reset/password/', auth_views.PasswordResetView.as_view(
        template_name='registration/reset.html',
        email_template_name='registration/reset_email.html',
        subject_template_name='registration/reset_subject.txt',
        success_url='/main/success/'
    )
         , name='reset'),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('success/', views.success, name='success'),
    path('contacto/', views.contacto, name='contacto'),
    path('success/reset/', views.success_reset, name='success_reset'),
    path('confirmacion/email/<token>', views.confirmar_registro, name='confirmar_registro')
]

contratar_musicos/musicos/urls.py
from django.urls import include, path
from django.contrib import admin
from contratar_musicos.musicos import views
app_name = 'musicos'

urlpatterns = [
    path('', views.index, name='index'),
    path('perfil/<slug:slug_musico>', views.perfil_musico, name='perfil_musico'),
    path('unetenos/', views.registro_usuario_musico, name='registro_usuario_musico'),
    path('completar-registro/', views.registro_musico, name='completar_registro_musico'),
    path('categoria/<slug:slug_tipo_musico>', views.tipo_musico, name='tipo_musico'),
    path('registro/visita/', views.registro_visitas, name='registro_visitas'),
    path('obtener/musico/tipo', views.obtener_musicos_tipo, name='obtener_musicos_tipo'),
]

contratar_musicos/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('main/', include('contratar_musicos.main.urls', namespace="main")),
                  path('', include('contratar_musicos.musicos.urls', namespace="musicos")),
                  path('accounts/', include('django.contrib.auth.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contratar_musicos/musicos/models.py
from django.db import models
from contratar_musicos.main.models import *
from contratar_musicos.main.utils import PathAndRename
from imagekit.models import ProcessedImageField
from imagekit.processors import Transpose
from django.template.defaultfilters import slugify

# Create your models here.
path_and_rename_musicos = PathAndRename("musicos")
TIPOS_PRECIOS = (
    (0, 'POR HORA'),
    (1, 'POR CANCION'),
    (2, 'POR EVENTO'),
    (3, 'GENERAL'),
)


class Musico(models.Model):
    usuario = models.ForeignKey('main.Usuario', related_name='musicos', on_delete=models.SET_DEFAULT, default=None)
    nombre = models.CharField(max_length=30)
    imagen_principal = ProcessedImageField(max_length=255, null=True,
                                           upload_to=path_and_rename_musicos,
                                           processors=[Transpose()])
    descripcion = models.TextField()
    valoracion = models.FloatField(null=True, blank=True, default=0)
    tipo_musico = models.ForeignKey('TipoMusico', related_name='musicos', on_delete=models.SET_DEFAULT, default=None)
    precio = models.ForeignKey('Precio', related_name='musicos', null=True, blank=True, on_delete=models.SET_DEFAULT,
                               default=None)
    estilo_musica = models.ManyToManyField('EstiloMusica', related_name='musico')
    servicio_musica = models.ManyToManyField('Servicios', related_name='musico')
    slug = models.SlugField(max_length=60, editable=False, unique=True, null=True, blank=True)
    demo = models.ForeignKey('Demo', blank=True, null=True, on_delete=models.SET_NULL)
    info_adicional = models.ManyToManyField('InfoAdicional')
    cantidad_visitas = models.IntegerField(default=0, blank=True, null=True)
    contacto = models.OneToOneField('Contacto', null=True, blank=True, related_name='musico',
                                    on_delete=models.SET_DEFAULT, default=None)

    # TODO revisar los precios para agregar

    def __str__(self):
        return self.nombre

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nombre)
        return super(Musico, self).save(*args, **kwargs)


class InfoAdicional(models.Model):
    pregunta = models.TextField(max_length=250)
    respuesta = models.TextField(max_length=250)

    def __str__(self):
        return self.pregunta


class EstiloMusica(models.Model):
    nombre = models.CharField(max_length=30)

    def __str__(self):
        return self.nombre


class TipoCobro(models.Model):
    nombre = models.CharField(max_length=30)

    def __str__(self):
        return self.nombre


class Precio(models.Model):
    valor_minimo = models.IntegerField()
    valor_maximo = models.IntegerField()
    tipo_cobro = models.ForeignKey('TipoCobro', on_delete=models.SET_DEFAULT, default=None)

    def __str__(self):
        return 'min:{} max:{}-{}'.format(self.valor_minimo, self.valor_maximo, self.tipo_cobro.nombre)


class Servicios(models.Model):
    nombre = models.CharField(max_length=30)

    def __str__(self):
        return self.nombre


class TipoMusico(models.Model):
    nombre = models.CharField(max_length=30)
    slug = models.SlugField(max_length=60, editable=False, unique=True, null=True, blank=True)

    def __str__(self):
        return self.nombre

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nombre)
        return super(TipoMusico, self).save(*args, **kwargs)


class GeoLocalizacion(models.Model):
    municipio = models.ForeignKey('main.Municipio', on_delete=models.CASCADE)
    estado = models.ForeignKey('main.Estado', on_delete=models.CASCADE)
    pais = models.ForeignKey('main.Pais', on_delete=models.CASCADE)
    musico = models.ForeignKey('Musico', related_name='localizacion', blank=True, null=True
                               , on_delete=models.CASCADE)

    def __str__(self):
        return "{}-{}-{}".format(self.municipio, self.estado, self.pais)


class Contacto(models.Model):
    telefono = models.CharField(max_length=12)
    email = models.CharField(max_length=30, null=True, blank=True)
    web = models.CharField(max_length=30, null=True, blank=True)
    facebook = models.CharField(max_length=30, null=True, blank=True)
    twitter = models.CharField(max_length=30, null=True, blank=True)
    instagram = models.CharField(max_length=30, null=True, blank=True)
    youtube = models.CharField(max_length=30, null=True, blank=True)

    def __str__(self):
        return self.telefono


class ImagenMusico(models.Model):
    image = models.FileField(null=True, blank=True)
    texto = models.CharField(max_length=100, blank=True, null=True)
    musico = models.ForeignKey('Musico', related_name='imagenes_galeria', blank=True, null=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.musico.slug


class TipoDemo(models.Model):
    nombre = models.CharField(max_length=30)

    def __str__(self):
        return self.nombre


class Demo(models.Model):
    nombre = models.CharField(max_length=150, default="Demo")
    video = models.CharField(max_length=150)
    audio = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.nombre

contratar_musicos/musicos/forms.py
from contratar_musicos.musicos.models import *
from django.forms import ModelForm

class ContactoForm(ModelForm):
    class Meta:
        model = Contacto
        fields = '__all__'


class LocalizacionForm(ModelForm):
    class Meta:
        model = GeoLocalizacion
        fields = '__all__'


class RegistroMusicoForm(ModelForm):
    # Embed form
    contacto = ContactoForm()
    localizacion = LocalizacionForm()

    class Meta:
        model = Musico
        fields = ('nombre', 'descripcion', 'tipo_musico', 'estilo_musica','servicio_musica', 'contacto')
        # exclude = ['usuario']


class UsuarioForm(ModelForm):
    class Meta:
        model = Usuario
        fields = ['email', 'username', 'password']

contratar_musicos/musicos/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from contratar_musicos.musicos.models import *
from contratar_musicos.musicos.forms import *
from django.http import HttpResponseRedirect, HttpResponse
from contratar_musicos.musicos.serializer import *
import json


# @login_required
def index(request):
    estado = Estado.objects.get(nombre="Queretaro")
    musicos = Musico.objects.filter(localizacion__estado=estado).order_by('-id')[:8]
    tipos_musicos = TipoMusico.objects.all()
    servicios = Servicios.objects.all()
    tipo_cobro = TipoCobro.objects.all()

    if request.method == 'POST':
        kwargs = {}

        if request.POST.get('nombre') is not "":
            kwargs['nombre__icontains'] = request.POST.get('nombre')

        if request.POST.get('tipo-musico') != "-1":
            tipo_musico_buscar = TipoMusico.objects.get(pk=request.POST.get('tipo-musico'))
            kwargs['tipo_musico'] = tipo_musico_buscar

        if request.POST.get('servicio') != "-1":
            servicios_buscar = Servicios.objects.get(pk=request.POST.get('servicio'))
            kwargs['servicio_musica'] = servicios_buscar

        if request.POST.get('precio-min') is not "" and request.POST.get('precio-max') is not "" and request.POST.get('tipo_cobro') != "-1":
            tipo_cobro_buscar = TipoCobro.objects.get(pk=request.POST.get('tipo_cobro'))
            precio_min_buscar = Precio.objects.filter(valor_minimo__lte=request.POST.get('precio-min'), valor_maximo__gte=request.POST.get('precio-max'), tipo_cobro=tipo_cobro_buscar)
            kwargs['precio__in'] = precio_min_buscar

        if request.POST.get('precio-min') is not "" and request.POST.get('precio-max') is not "" and request.POST.get('tipo_cobro') == "-1":
            precio_min_buscar = Precio.objects.filter(valor_minimo__lte=request.POST.get('precio-min'), valor_maximo__gte=request.POST.get('precio-max'))
            kwargs['precio__in'] = precio_min_buscar

        resultado_busqueda = Musico.objects.filter(**kwargs)
        context = {'resultado_busqueda': resultado_busqueda}
        return render(request, 'musicos/resultado_busqueda.html', context=context)

    context = {
        'musicos': musicos,
        'tipos_musicos': tipos_musicos,
        'servicios': servicios,
        'tipo_cobro': tipo_cobro
    }
    return render(request, 'musicos/index.html', context)


def registro_visitas(request):
    id_musico = request.GET.get('musico')
    try:
        musico = Musico.objects.get(slug=id_musico)
        cantidad_visita = musico.cantidad_visitas + 1
        musico.cantidad_visitas = cantidad_visita
        musico.save()
        json_data = {'rc': 0, 'msg': 'Exito'}

    except Musico.DoesNotExist:
        json_data = {'rc': -1, 'msg': 'Los datos que intenta ver no existen. Lo sentimos'}

    return HttpResponse(json.dumps(json_data), content_type='application/json')


def tipo_musico(request, slug_tipo_musico):
    tipo = TipoMusico.objects.get(slug=slug_tipo_musico)
    musicos = Musico.objects.filter(tipo_musico=tipo)
    context = {'musicos':musicos, 'tipo_musico': tipo}

    return render(request, 'musicos/tipos_musico.html', context=context)


def perfil_musico(request, slug_musico):
    try:
        musico = Musico.objects.get(slug=slug_musico)
        for imagen in musico.imagenes_galeria.all():
            print(imagen.image.url)
    except Musico.DoesNotExist:
        musico = None
    return render(request, 'musicos/perfil_musico.html', {'musico': musico})


def registro_musico(request):
    form = RegistroMusicoForm()
    if request.method == 'POST':
        form = RegistroMusicoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')

    return render(request, 'musicos/registro_musico.html', {'form': form })


def registro_usuario_musico(request):
    form = UsuarioForm()
    if request.method == 'POST':
        form = UsuarioForm(request.POST)
        # form.username = form.email
        if form.is_valid():
            usuario = form.save()
            request.session.pop('registered_user', usuario.pk)
            musico_form = RegistroMusicoForm()
            return render(request, 'musicos/registro_musico.html', {'form': musico_form})

    return render(request, 'musicos/registro_usuario_musico.html', {'form': form})


def obtener_musicos_tipo(request):
    slug_tipo_musico = request.GET['tipo_musico']
    tipo = TipoMusico.objects.get(slug=slug_tipo_musico)
    musicos = Musico.objects.filter(tipo_musico=tipo)
    serial = MusicoSerializer(musicos, many=True)
    json_data = {
        'msg': 'Ok',
        'rc': '0',
        'data': serial.data
    }
    return HttpResponse(json.dumps(json_data),content_type='application/json')

contratar_musicos/musicos/templates/musicos/base.html
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}
    <!-- Basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Contratar músicos </title>
    {#    TODO HACER ESTOS METAS#}
    <meta name="keywords" content=""/>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Favicon -->
    <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon"/>
    <link rel="apple-touch-icon" href="img/apple-touch-icon.png">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <!--Vendors-->
    <link rel="stylesheet" href="{% static 'musicos/css/font-awesome/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'musicos/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'musicos/css/normalize.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/buttons-min.css">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/forms-min.css">
    {#    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/menus-min.css">#}

    {% block stylesheets %}

    {% endblock %}
</head>
<body>
<header class="header">
    <picture>
        <img src="{% static 'musicos/img/logo.png' %}" title="Logo" width="100px">
    </picture>
    <nav class="nav">
        <label for="show-menu" class="show-menu show-btn__visibility show-btn__size">
            <i class="fa fa-bars"></i>
        </label>
        <input type="checkbox" id="show-menu" role="button">
        <ul class="menu-header">
            <li class="menu-header--item">
                <a class="menu-header--link" href="{% url 'musicos:index' %}">Inicio</a>
            </li>

            <li class="menu-header--item dropdown">
                <a href="" class="dropbtn menu-header--link">Musicos</a>
                <ul class="dropdown-content">
                    <li><a href="">asdasdsa</a></li>
                    {% for tipo in tipos_musico %}
                        <li>
                            <a href="{% url 'musicos:tipo_musico' slug_tipo_musico=tipo.slug %}">{{ tipo }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </li>
            <li class="menu-header--item"><a class="menu-header--link"
                                             href="{% url 'musicos:registro_usuario_musico' %}">Únetenos</a></li>
            <li class="menu-header--item"><a class="menu-header--link" href="{% url 'login' %}">Entrar al perfil</a>
            </li>
            <li class="menu-header--item"><a class="menu-header--link" href="{% url 'main:contacto' %}">Contacto</a>
            </li>
        </ul>
    </nav>
</header>
{% block container %}

{% endblock %}
<footer class="row">
    <p class="text-center">Todos los derechos reservados. 2017</p>
</footer>

{% block javascripts %}{% endblock %}
</body>
</html>

contratar_musicos/musicos/templates/musicos/datos_contacto_musico.html
{% load staticfiles %}
<div class="modal fade" id="datos-contacto-modal{{ musico.pk }}" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Datos contacto</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    {% if musico.contacto.telefono %}
                        <div class="col-sm-6" id="telefono-contacto">
                            <img
                                    src="{% static 'musicos/img/social/ph.png' %}"
                                    alt="telefono"
                                    class="pull-left mr5" width="30px"
                            >
                            {{ musico.contacto.telefono }}
                        </div>
                    {% endif %}
                    {% if musico.contacto.email %}
                        <div class="col-sm-6" id="email-contacto">
                            <img
                                    src="{% static 'musicos/img/social/email.png' %}"
                                    alt="email"
                                    class="pull-left mr5" width="30px"
                            >
                            <a href="mailto:{{ musico.contacto.email }}">{{ musico.contacto.email }}</a>
                        </div>
                    {% endif %}
                    {% if musico.contacto.web %}
                        <div class="col-sm-6" id="web-web">
                            <img
                                    src="{% static 'musicos/img/social/web.png' %}"
                                    alt="web"
                                    class="pull-left mr5" width="30px"
                            >
                            <a href="{{ musico.contacto.web }}" id="link-web">{{ musico.contacto.web }}</a>
                        </div>
                    {% endif %}
                    {% if musico.contacto.facebook %}
                        <div class="col-sm-6" id="facebook-contacto">
                            <img
                                    src="{% static 'musicos/img/social/fb.png' %}"
                                    alt="facebook"
                                    class="pull-left mr5" width="30px"
                            >
                            <a href="{{ musico.contacto.facebook }}"
                               id="link-facebook">{{ musico.contacto.facebook }}</a>
                        </div>
                    {% endif %}
                    {% if musico.contacto.twitter %}
                        <div class="col-sm-6" id="twitter-contacto">
                            <img
                                    src="{% static 'musicos/img/social/tw.png' %}"
                                    alt="tw"
                                    class="pull-left mr5" width="30px"
                            >
                            <a href="{{ musico.contacto.twitter }}"
                               id="link-twitter">{{ musico.contacto.twitter }}</a>
                        </div>
                    {% endif %}
                    {% if musico.contacto.instagram %}
                        <div class="col-sm-6" id="twitter-instagram">
                            <img
                                    src="{% static 'musicos/img/social/inst.png' %}"
                                    alt="inst"
                                    class="pull-left mr5" width="30px"
                            >
                            <a href="{{ musico.contacto.instagram }}"
                               id="link-instagram">{{ musico.contacto.instagram }}</a>
                        </div>
                    {% endif %}
                    {% if musico.contacto.youtube %}
                        <div class="col-sm-6" id="twitter-youtube">
                            <img
                                    src="{% static 'musicos/img/social/yt.png' %}"
                                    alt="yt"
                                    class="pull-left mr5" width="30px"
                            >
                            <a href="{{ musico.contacto.youtube }}"
                               id="link-youtube">{{ musico.contacto.youtube }}</a>
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

contratar_musicos/musicos/templates/musicos/item_musico.html
{% load thumbnail %}
<div class="col-sm-3">
    <div class="item-musico">

        <a href="{% url 'musicos:perfil_musico' slug_musico=musico.slug %}">
            <div style="background: url('{{ musico.imagen_principal|thumbnail_url:'thumb_musico_index' }}')"
                 class="img-thumbnail-video"></div>
        </a>
        <div class="container-info pd15">
            <a class="bold" href="{% url 'musicos:perfil_musico' slug_musico=musico.slug %}">{{ musico.nombre }}</a>
            <p class="bold text-naranja">{{ musico.tipo_musico }}</p>

            <p class="fs12">{{ musico.descripcion|truncatechars:'65' }}</p>
            <div class="container-social-icons">
                <div class="container-demo">
                    {% if musico.demo.video != None %}
                        <a href="{{ musico.demo.video }}" target="_blank">Ver demo</a>
                    {% endif %}
                    {% if musico.demo.audio != None %}
                        <audio controls style="width: 100%">
                            <source src="{{ musico.demo.audio.url }}" type="audio/mpeg">
                            Su navegador no soporta los audios. Por favor cambie a Firefox o Chrome
                        </audio>
                    {% endif %}
                </div>
                <div class="btn bg-naranja btn-block text-blanco"
                     data-toggle="modal"
                     data-target="#datos-contacto-modal{{ musico.pk }}">
                    Ver info contacto
                </div>
            </div>
        </div>
    </div>
</div>
{% include 'musicos/datos_contacto_musico.html' %}

contratar_musicos/musicos/templates/musicos/registro_musico.html
{% extends 'musicos/base.html' %}
{% block container %}
    <div class="container mt10">
        <div class="row well">
            <h4 class="text-naranja text-center">Si eres músico y quieres pertenecer a esta increible comunidad. Date de
                alta
                aquí</h4>
            <hr>
            <form id="registro-musico-form" action="{% url 'musicos:completar_registro_musico' %}" method="POST" enctype="multipart/form-data" class="form-group">
                <div class="row">
                    <div class="col-sm-8">
                        <label>Nombre:</label>
                        <div class="input-group">
                            <div class="input-group-addon">abc</div>
                            {{ form.nombre }}
                        </div>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-4">
                        <label>Descripción general</label>
                        {{ form.descripcion }}
                    </div>
                    <div class="col-sm-4">
                        <label for="tipo_musico">Tipo de músico</label>
                        {{ form.tipo_musico }}
                    </div>

                    <div class="col-sm-4">
                        <label for="tipo_musico">Estilos de música que manejan</label>
                        {{ form.estilo_musica }}
                        <p class="mark fs12">Puede seleccionar varios apretando la tecla Ctrl y sin soltarla clic en el
                            estilo que desee</p>
                    </div>

                </div>
                <h4 class="text-center text-naranja">Datos de contacto</h4>
                <hr>
                <div class="row">
                    <div class="col-sm-4">
                        <label>Telefono</label>
                        <div class="input-group">
                            <div class="input-group-addon"><i class="fa fa-phone"></i></div>
                            {{ form.contacto }}
                        </div>
                    </div>

                </div>

                <h4 class="text-center text-naranja">Información musical</h4>
                <hr>
                <div class="row">
                    <div class="col-sm-6">
                        <label>Eventos en que pude participar</label>
                        {{ form.servicio_musica }}
                    </div>
                     <div class="col-sm-6">
                        <label>Estado</label>
                        {{ form.localizacion.estado }}
                    </div>
                </div>
                {% csrf_token %}
                <button class="btn btn-block bg-naranja text-blanco mt10">Guardar</button>
            </form>
        </div>
    </div>
{% endblock %}

contratar_musicos/musicos/templates/musicos/registro_usuario_musico.html
{% extends 'musicos/base.html' %}
{% block container %}
    <div class="container mt10">
        <div class="row well">
            <h4 class="text-naranja text-center">Si eres músico y quieres pertenecer a esta increible comunidad. Date de
                alta
                aquí</h4>
            <hr>
            <form id="registro-musico-form" action="#" method="POST" enctype="multipart/form-data" class="form-group">
                <div class="row">
                    {% csrf_token %}
                    <div class="col-sm-6">
                        <label>Correo Electrónico:</label>
                        <div class="input-group">
                            <div class="input-group-addon">@</div>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <label>Contraseña:</label>
                        <div class="input-group">
                            <div class="input-group-addon">***</div>
                            {{ form.password }}
                        </div>
                    </div>
                    <div class="d-none">
                        {{ form.username }}
                    </div>
                    <div class="col-sm-12 mt10">
                        <button class="btn bg-naranja text-blanco">REGISTRARSE</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script>
        let password = document.querySelector('#id_password').type = 'password'
        let email = document.querySelector('#id_email')
        let username = document.querySelector('#id_username')
        email.addEventListener('change', function (event) {
            username.value = event.target.value
        } )
    </script>
{% endblock %}

contratar_musicos/musicos/templates/musicos/resultado_busqueda.html
{% extends 'musicos/base.html' %}
{% load staticfiles %}
{% block container %}
    <div class="container">
        <h4 class="ml80">Resultados de b&uacute;squeda</h4>
        <hr>
        <section id="container-categorias">
            {% if resultado_busqueda|length > 0 %}
                {% for musico in resultado_busqueda %}
                    {% include 'musicos/item_musico.html' with musico=musico %}
                {% endfor %}
            {% else %}
                <h4 class="ml80">Upss :( Lo sentimos pero no tenemos m&uacute;sicos con esas caracter&iacute;sticas</h4>
            {% endif %}
        </section>
    </div>
{% endblock %}

contratar_musicos/musicos/templates/musicos/tipos_musico.html
{% extends 'musicos/base.html' %}
{% load staticfiles %}
{% block container %}
    <div class="container mt10">
        <h4 class="ml80  text-naranja">Est&aacute;s viendo <b>{{ tipo_musico }}</b></h4>
        <hr>
        <section id="container-categorias">
            {% if musicos|length > 0 %}
                {% for musico in musicos %}
                    {% include 'musicos/item_musico.html' with musico=musico %}
                {% endfor %}
            {% else %}
                <h4 class="ml80 alert alert-danger">Upss :( Lo sentimos pero no tenemos m&uacute;sicos en esta categor&iacute;a</h4>
            {% endif %}
        </section>
    </div>
{% endblock %}